call C:\Users\deniz.kilic\AppData\Local\Continuum\anaconda3\Scripts\activate.bat C:\Users\deniz.kilic\AppData\Local\Continuum\anaconda3
python E:\CD_Codes\changeDetectionPerformanceTool.py E:\CD_Codes\Celik\cd2014_thermal\component2bs2\Inputs_of_Change_Detection_Performance_Tool.xls E:\CD_Codes\Celik\cd2014_thermal\component2bs2\performance_results.xlsx
python E:\CD_Codes\changeDetectionPerformanceTool.py E:\CD_Codes\Celik\cd2014_thermal\component2bs3\Inputs_of_Change_Detection_Performance_Tool.xls E:\CD_Codes\Celik\cd2014_thermal\component2bs3\performance_results.xlsx
python E:\CD_Codes\changeDetectionPerformanceTool.py E:\CD_Codes\Celik\cd2014_thermal\component2bs4\Inputs_of_Change_Detection_Performance_Tool.xls E:\CD_Codes\Celik\cd2014_thermal\component2bs4\performance_results.xlsx
python E:\CD_Codes\changeDetectionPerformanceTool.py E:\CD_Codes\Celik\cd2014_thermal\component2bs5\Inputs_of_Change_Detection_Performance_Tool.xls E:\CD_Codes\Celik\cd2014_thermal\component2bs5\performance_results.xlsx
python E:\CD_Codes\changeDetectionPerformanceTool.py E:\CD_Codes\Celik\cd2014_thermal\component2bs6\Inputs_of_Change_Detection_Performance_Tool.xls E:\CD_Codes\Celik\cd2014_thermal\component2bs6\performance_results.xlsx
python E:\CD_Codes\changeDetectionPerformanceTool.py E:\CD_Codes\Celik\cd2014_thermal\component2bs7\Inputs_of_Change_Detection_Performance_Tool.xls E:\CD_Codes\Celik\cd2014_thermal\component2bs7\performance_results.xlsx
python E:\CD_Codes\changeDetectionPerformanceTool.py E:\CD_Codes\Celik\cd2014_thermal\component2bs8\Inputs_of_Change_Detection_Performance_Tool.xls E:\CD_Codes\Celik\cd2014_thermal\component2bs8\performance_results.xlsx
python E:\CD_Codes\changeDetectionPerformanceTool.py E:\CD_Codes\Celik\cd2014_thermal\component3bs2\Inputs_of_Change_Detection_Performance_Tool.xls E:\CD_Codes\Celik\cd2014_thermal\component3bs2\performance_results.xlsx
python E:\CD_Codes\changeDetectionPerformanceTool.py E:\CD_Codes\Celik\cd2014_thermal\component3bs3\Inputs_of_Change_Detection_Performance_Tool.xls E:\CD_Codes\Celik\cd2014_thermal\component3bs3\performance_results.xlsx
python E:\CD_Codes\changeDetectionPerformanceTool.py E:\CD_Codes\Celik\cd2014_thermal\component3bs4\Inputs_of_Change_Detection_Performance_Tool.xls E:\CD_Codes\Celik\cd2014_thermal\component3bs4\performance_results.xlsx
python E:\CD_Codes\changeDetectionPerformanceTool.py E:\CD_Codes\Celik\cd2014_thermal\component3bs5\Inputs_of_Change_Detection_Performance_Tool.xls E:\CD_Codes\Celik\cd2014_thermal\component3bs5\performance_results.xlsx
python E:\CD_Codes\changeDetectionPerformanceTool.py E:\CD_Codes\Celik\cd2014_thermal\component3bs6\Inputs_of_Change_Detection_Performance_Tool.xls E:\CD_Codes\Celik\cd2014_thermal\component3bs6\performance_results.xlsx
python E:\CD_Codes\changeDetectionPerformanceTool.py E:\CD_Codes\Celik\cd2014_thermal\component3bs7\Inputs_of_Change_Detection_Performance_Tool.xls E:\CD_Codes\Celik\cd2014_thermal\component3bs7\performance_results.xlsx
python E:\CD_Codes\changeDetectionPerformanceTool.py E:\CD_Codes\Celik\cd2014_thermal\component3bs8\Inputs_of_Change_Detection_Performance_Tool.xls E:\CD_Codes\Celik\cd2014_thermal\component3bs8\performance_results.xlsx
